version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    command: python3 manage.py test
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
