# Generated by Django 2.2.10 on 2020-02-23 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pinid', models.UUIDField()),
                ('volunteerid', models.UUIDField()),
                ('taskid', models.UUIDField()),
                ('archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversationid', models.UUIDField()),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('senderid', models.UUIDField()),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swiperid', models.UUIDField()),
                ('swipedid', models.UUIDField()),
                ('taskid', models.UUIDField()),
                ('matched', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=5000)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('pinid', models.UUIDField()),
                ('volunteerid', models.UUIDField()),
                ('state', models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'POSTED'), (2, 'COMMITTED PIN'), (3, 'COMMITTED CONSENSUS'), (4, 'COMPLETED ONE'), (5, 'COMPLETED CONSENSUS')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('oauthid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('photourl', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=5000)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
