# Generated by Django 2.2.10 on 2020-03-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200227_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
