# Generated by Django 2.2.10 on 2020-03-03 22:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200303_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='embedding_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=100),
        ),
    ]
