# Generated by Django 2.2.10 on 2020-03-03 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_embedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='embedding_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=768),
        ),
    ]
