# Generated by Django 2.2.10 on 2020-03-03 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200303_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='embedding_vector',
            new_name='description_embedding',
        ),
        migrations.AddField(
            model_name='user',
            name='bio_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=768),
        ),
    ]
